package r4t2.git.storm.output;

import com.google.gson.*;
import r4t2.git.storm.mappings.ItemMapping;
import r4t2.git.storm.pack.PackIndex;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Assembles the Bedrock Edition .mcpack resource pack ZIP file.
 *
 * Pack structure:
 * storm_resources.mcpack
 *  +--- manifest.json
 *  +--- textures/
 *  |   +--- item_texture.json           <- short-key -> path map
 *  |   \--- items/storm/               <- converted item PNGs
 *  +--- models/entity/storm/           <- geometry.json files for 3D items
 *  \--- font/
 *      \--- glyph_E0.png, ...          <- Bedrock glyph pages
 */
public class McpackBuilder {

    private static final String PACK_NAME = "Storm Resources";
    private static final String PACK_DESCRIPTION = "Custom items and fonts generated by Storm";
    private static final int FORMAT_VERSION = 2;

    private final Path outputDir;
    private final PackIndex sourceIndex;
    private final Gson gson = new GsonBuilder().setPrettyPrinting().create();

    public McpackBuilder(Path outputDir, PackIndex sourceIndex) {
        this.outputDir = outputDir;
        this.sourceIndex = sourceIndex;
    }

    /**
     * Builds the .mcpack and writes it to the output directory.
     *
     * @param mappings   All converted item mappings.
     * @param glyphPages Bedrock glyph pages: page name (e.g. "E0") -> PNG bytes.
     * @return Path to the written .mcpack file.
     */
    public Path build(List<ItemMapping> mappings, Map<String, byte[]> glyphPages) throws IOException {
        Path mcpackPath = outputDir.resolve("storm_resources.mcpack");

        try (ZipOutputStream zip = new ZipOutputStream(Files.newOutputStream(mcpackPath))) {
            writeEntry(zip, "manifest.json", buildManifest().getBytes(StandardCharsets.UTF_8));
            writeEntry(zip, "textures/item_texture.json",
                    buildItemTexture(mappings).getBytes(StandardCharsets.UTF_8));
            Set<String> copiedTextures = new HashSet<>();
            for (ItemMapping mapping : mappings) {
                String src = mapping.getSourceTexturePath();
                String dest = "textures/items/storm/" + mapping.getBedrockTextureKey() + ".png";
                if (copiedTextures.add(dest)) {
                    byte[] pngBytes = sourceIndex.get(src);
                    if (pngBytes != null) {
                        writeEntry(zip, dest, pngBytes);
                    }
                }
            }

            Map<String, BedrockGeometry> geoMap = new LinkedHashMap<>();
            for (ItemMapping mapping : mappings) {
                if (mapping.isGeometry() && mapping.getGeometry() != null) {
                    BedrockGeometry geo = mapping.getGeometry();
                    geoMap.put(geo.getIdentifier(), geo);
                }
            }

            if (!geoMap.isEmpty()) {
                String geoJson = buildGeometryJson(geoMap);
                writeEntry(zip, "models/entity/storm/storm_items.geo.json",
                        geoJson.getBytes(StandardCharsets.UTF_8));
            }

            for (Map.Entry<String, byte[]> page : glyphPages.entrySet()) {
                String pagePath = "font/glyph_" + page.getKey() + ".png";
                writeEntry(zip, pagePath, page.getValue());
            }
        }

        return mcpackPath;
    }


    private String buildManifest() {
        JsonObject root = new JsonObject();
        root.addProperty("format_version", FORMAT_VERSION);

        String contentSeed = sourceIndex.allPaths().stream().sorted().collect(Collectors.joining(","));
        UUID headerUuid = UUID.nameUUIDFromBytes(("storm.header." + contentSeed).getBytes(StandardCharsets.UTF_8));
        UUID moduleUuid = UUID.nameUUIDFromBytes(("storm.module." + contentSeed).getBytes(StandardCharsets.UTF_8));
        JsonObject header = new JsonObject();
        header.addProperty("name", PACK_NAME);
        header.addProperty("description", PACK_DESCRIPTION);
        header.add("uuid", new JsonPrimitive(headerUuid.toString()));
        header.add("version", versionArray(1, 0, 0));
        header.add("min_engine_version", versionArray(1, 20, 0));
        root.add("header", header);
        JsonArray modules = new JsonArray();
        JsonObject mod = new JsonObject();
        mod.addProperty("type", "resources");
        mod.add("uuid", new JsonPrimitive(moduleUuid.toString()));
        mod.add("version", versionArray(1, 0, 0));
        modules.add(mod);
        root.add("modules", modules);
        return gson.toJson(root);
    }

    private String buildItemTexture(List<ItemMapping> mappings) {
        JsonObject root = new JsonObject();
        root.addProperty("resource_pack_name", "storm");
        root.addProperty("texture_name", "atlas.items");
        JsonObject textureData = new JsonObject();
        Set<String> seen = new HashSet<>();
        for (ItemMapping mapping : mappings) {
            String key = mapping.getBedrockTextureKey();
            if (seen.add(key)) {
                JsonObject entry = new JsonObject();
                entry.addProperty("textures", "textures/items/storm/" + key);
                textureData.add(key, entry);
            }
        }
        root.add("texture_data", textureData);
        return gson.toJson(root);
    }

    private String buildGeometryJson(Map<String, BedrockGeometry> geoMap) {
        JsonObject root = new JsonObject();
        root.addProperty("format_version", BedrockGeometry.FORMAT_VERSION);
        JsonArray geometries = new JsonArray();
        for (BedrockGeometry geo : geoMap.values()) {
            geometries.add(serializeGeometry(geo));
        }
        root.add("minecraft:geometry", geometries);
        return gson.toJson(root);
    }

    private JsonObject serializeGeometry(BedrockGeometry geo) {
        JsonObject obj = new JsonObject();

        JsonObject desc = new JsonObject();
        desc.addProperty("identifier", geo.getIdentifier());
        desc.addProperty("texture_width", geo.getTextureWidth());
        desc.addProperty("texture_height", geo.getTextureHeight());
        desc.addProperty("visible_bounds_width", 2.0f);
        desc.addProperty("visible_bounds_height", 2.5f);
        desc.add("visible_bounds_offset", floatArray(new float[]{0, 0.75f, 0}));
        obj.add("description", desc);

        JsonArray bones = new JsonArray();
        for (BedrockGeometry.Bone bone : geo.getBones()) {
            bones.add(serializeBone(bone));
        }
        obj.add("bones", bones);

        return obj;
    }

    private JsonObject serializeBone(BedrockGeometry.Bone bone) {
        JsonObject obj = new JsonObject();
        obj.addProperty("name", bone.getName());
        obj.add("pivot", floatArray(bone.getPivot()));

        float[] rot = bone.getRotation();
        if (rot[0] != 0 || rot[1] != 0 || rot[2] != 0) {
            obj.add("rotation", floatArray(rot));
        }

        JsonArray cubes = new JsonArray();
        for (BedrockGeometry.BoneCube cube : bone.getCubes()) {
            cubes.add(serializeCube(cube));
        }
        obj.add("cubes", cubes);

        return obj;
    }

    private JsonObject serializeCube(BedrockGeometry.BoneCube cube) {
        JsonObject obj = new JsonObject();
        obj.add("origin", floatArray(cube.getOrigin()));
        obj.add("size", floatArray(cube.getSize()));

        if (cube.getPerFaceUv() != null) {
            BedrockGeometry.PerFaceUv pf = cube.getPerFaceUv();
            JsonObject uvObj = new JsonObject();
            if (pf.north != null) uvObj.add("north", faceUvEntry(pf.north));
            if (pf.south != null) uvObj.add("south", faceUvEntry(pf.south));
            if (pf.east  != null) uvObj.add("east",  faceUvEntry(pf.east));
            if (pf.west  != null) uvObj.add("west",  faceUvEntry(pf.west));
            if (pf.up    != null) uvObj.add("up",    faceUvEntry(pf.up));
            if (pf.down  != null) uvObj.add("down",  faceUvEntry(pf.down));
            obj.add("uv", uvObj);
        } else {
            obj.add("uv", floatArray(cube.getUv()));
        }

        return obj;
    }

    private JsonObject faceUvEntry(float[] uv) {
        JsonObject obj = new JsonObject();
        JsonArray uvArr = new JsonArray();
        uvArr.add(uv[0]);
        uvArr.add(uv[1]);
        obj.add("uv", uvArr);
        JsonArray sizeArr = new JsonArray();
        sizeArr.add(uv[2]);
        sizeArr.add(uv[3]);
        obj.add("uv_size", sizeArr);
        return obj;
    }

    private void writeEntry(ZipOutputStream zip, String path, byte[] data) throws IOException {
        zip.putNextEntry(new ZipEntry(path));
        zip.write(data);
        zip.closeEntry();
    }

    private JsonArray floatArray(float[] arr) {
        JsonArray ja = new JsonArray();
        for (float f : arr) ja.add(f);
        return ja;
    }

    private JsonArray versionArray(int major, int minor, int patch) {
        JsonArray ja = new JsonArray();
        ja.add(major); ja.add(minor); ja.add(patch);
        return ja;
    }
}
